#!/bin/bash

# Update the system
sudo apt update
sudo apt upgrade -y

# Install Xorg
sudo apt install xorg -y

# Disable automatic start of Xorg
sudo systemctl set-default multi-user.target

# Create a script to start Xorg when a graphical app is launched
echo -e '#!/bin/bash\nxinit $(which gnome-terminal)' > ~/.xstart
chmod +x ~/.xstart

# Add a line to .bashrc to start Xorg when a graphical app is launched
echo -e '\nif [ -n "$DISPLAY" ] && [ "$TERM" == "xterm" ]; then\n    exec startx\nfi' >> ~/.bashrc